# Generated by Django 3.2.18 on 2023-02-21 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(default='default_machine', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(default='default_machine', max_length=200)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('dose_id', models.AutoField(primary_key=True, serialize=False)),
                ('dose', models.FloatField(max_length=25)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.patient')),
            ],
        ),
    ]
